### PR TITLE
Changed the data order for the graph

### PR DESCRIPTION
**Pull request by GabrielRodriguez66**

### CODE REVIEW

**Comment by GabrielRodriguez66** [comment]
Fixed #17

**Comment by GabrielRodriguez66** [comment]
Implemented #22

**Comment by jaortiz117** [comment]
Is issue #22 solved? are the functions updated?

**Comment by GabrielRodriguez66** [comment]
Yeah, I added the new parameters to the controller functions. It needs to be tested with the Python code

**Comment by GabrielRodriguez66** [comment]
I tested the methods with my own Py code and with the new DB changes and it works fine

**Comment by jaortiz117** [comment]
awesome gonna merge it

**Pull request merged**
