### PR TITLE
Postgres and Sequelize documentation

### PR DESCRIPTION
**Pull request by Everod52**
The documentation is under the file "db_orm_setup.md"

### CODE REVIEW

**Comment by jaortiz117** [comment]
please place this file in the docs folder of the repo under a new directory called "db-orm". Also change the file name to "SETUP.md"

**Comment by Everod52** [comment]
@jaortiz117 Done!

**Comment by Everod52** [comment]
Found issue with importing environment variables. DO NOT MERGE

**Comment by Everod52** [comment]
Fixed issue, application tested and ready to merge.

**Pull request merged**
